### ISSUE TITLE
Integrate sensors with database

### ISSUE THREAD

**Issue by TechAUmNu** [IonSystems/tiberius-robot#43]
The data from the sensors needs to be constantly read and put in the database, which will allow multiple modules to be querying the sensor data at the same time. It will also allow analysis of the data to check its sanity

**Comment by camieac** [comment]
`PolyhedraDatabase` is good to go! See 16949cdcab0ccbcd2c7a08e1925ca6e79953eca2 and #32.

**Comment by camieac** [comment]
You're probably going to need another week.

**Comment by camieac** [comment]
Sensor data should also be sanity checked before insertion, and insane data should be ignored.

**Comment by camieac** [comment]
@apg30, you're in charge of this one now. @AndrewRigg feel free to work with @apg30 as you were doing.

**Comment by camieac** [comment]
I'm closing this, seems like the last of it was done in commit 32f3556cfc05ebd069a8817387a62c2339260f19
