### ISSUE TITLE
Raspberry Pi Camera Live Stream # 1

### ISSUE THREAD

**Issue by camieac** [IonSystems/tiberius-robot#45]
**Raspberry Pi Camera Live Stream # 1: Pi End**
Raspberry Pi Camera Live Stream # 2: Web End

Stream video from the Raspberry Pi Camera using UDP. It would be nice if we could use Python for this, since we use it to do everything else (not the best reasoning I know).

There seems to be a few solutions online that do pretty much what we want([Stack Exchange](http://raspberrypi.stackexchange.com/questions/23182/how-to-stream-video-from-raspberry-pi-camera-and-watch-it-live) and [Python example](http://www.pyimagesearch.com/2015/03/30/accessing-the-raspberry-pi-camera-with-opencv-and-python/))

This stream is going to be received by a socket on the web interface, to display a live(-ish) image so the user can see where they are going.

# Latency
We want to minimise this as much as possible because the camera will be used to control Tiberius when it is out of sight. We may need to compromise on resolution to keep the bandwidth low. A solution that makes efficient use of bandwidth is preferable, making use of compressi

**Comment by TechAUmNu** [comment]
Also chillipeppr has a webrtc viewer here which we can use:
http://jsfiddle.net/lordmundi/jrrhjnak/
